// <auto-generated />
using System;
using Lykke.Service.PushNotifications.MsSqlRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lykke.Service.PushNotifications.MsSqlRepositories.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200310094452_ColumnsChange")]
    partial class ColumnsChange
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("push_notifications")
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lykke.Service.PushNotifications.Domain.PushNotificationRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PushRegistrationToken")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("push_notification_registrations");
                });

            modelBuilder.Entity("Lykke.Service.PushNotifications.MsSqlRepositories.Entities.NotificationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnName("creation_timestamp");

                    b.Property<string>("CustomPayload")
                        .IsRequired()
                        .HasColumnName("custom_payload")
                        .HasMaxLength(4000);

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnName("customer_id")
                        .HasMaxLength(50);

                    b.Property<bool>("IsRead")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnName("message")
                        .HasMaxLength(10000);

                    b.Property<string>("MessageGroupId")
                        .IsRequired()
                        .HasColumnName("message_group_id")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CreationTimestamp");

                    b.HasIndex("CustomerId");

                    b.HasIndex("IsRead");

                    b.HasIndex("MessageGroupId")
                        .IsUnique();

                    b.ToTable("NotificationMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
