// <auto-generated />
using System;
using MAVN.Service.PushNotifications.MsSqlRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MAVN.Service.PushNotifications.MsSqlRepositories.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200706064759_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("push_notifications")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MAVN.Service.PushNotifications.Domain.PushNotificationRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PushRegistrationToken")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("SELECT CURRENT_TIMESTAMP at time zone 'utc'");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("push_notification_registrations");
                });

            modelBuilder.Entity("MAVN.Service.PushNotifications.MsSqlRepositories.Entities.NotificationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnName("creation_timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CustomPayload")
                        .IsRequired()
                        .HasColumnName("custom_payload")
                        .HasColumnType("character varying(4000)")
                        .HasMaxLength(4000);

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnName("customer_id")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsRead")
                        .HasColumnName("is_read")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnName("message")
                        .HasColumnType("character varying(10000)")
                        .HasMaxLength(10000);

                    b.Property<string>("MessageGroupId")
                        .IsRequired()
                        .HasColumnName("message_group_id")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CreationTimestamp");

                    b.HasIndex("CustomerId");

                    b.HasIndex("IsRead");

                    b.HasIndex("MessageGroupId")
                        .IsUnique();

                    b.ToTable("NotificationMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
